// =====================================================
// ARCHIVO: app/layout.tsx
// PROPÓSITO: Layout principal de la aplicación
// =====================================================

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from '@/context/AuthContext';
import "./globals.css";
import Navbar from './components/Navbar';

// =====================================================
// CONFIGURACIÓN DE FUENTES
// =====================================================

// Configura la fuente Geist Sans
// variable: define una variable CSS "--font-geist-sans" para usarla en Tailwind
// subsets: ["latin"] → carga solo los caracteres latinos (más liviano)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Configura la fuente Geist Mono (monoespaciada para código)
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// =====================================================
// METADATA DE LA PÁGINA (SEO)
// =====================================================

// Define el título y descripción que aparecen en la pestaña del navegador
export const metadata: Metadata = {
  title: "Create Next App",           // Título de la página
  description: "Generated by create next app", // Descripción para SEO
};

// =====================================================
// COMPONENTE PRINCIPAL (RootLayout)
// =====================================================

// Este componente envuelve TODAS las páginas de la aplicación
// Los archivos en app/ son Server Components por defecto, pero usamos "use client" en los que necesitan estado
export default function RootLayout({
  children,  // children → todas las páginas hijas (home, cursos, login, etc.)
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // html: elemento raíz del documento
    <html
      lang="en"                                   // idioma del documento
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      // ^ aplica las variables CSS de las fuentes + altura completa + antialiasing
    >
      {/* body: contenido visible */}
      <body className="min-h-full flex flex-col">
        {/* 
          AuthProvider: provee el contexto de autenticación a TODAS las páginas
          Cualquier componente hijo puede usar useAuth() para acceder a:
          - user (datos del usuario)
          - token
          - login(), register(), logout()
        */}
        <AuthProvider>
           <Navbar /> 
          {children}  {/* Aquí se renderiza la página actual (home, cursos, login, etc.) */}
        </AuthProvider>
      </body>
    </html>
  );
}